### ISSUE TITLE
Recent name change can cause confusing import error

### ISSUE THREAD

**Issue by sveinugu** [conda-forge/prompt_toolkit-feedstock#44] opened 2020-06-18 00:51 UTC
@jakirkham @ocefpaf 
For certain install/update scenarios, the `prompt_toolkit` package can end up in a non-working state, causing import errors:

```
Traceback (most recent call last):
  File "/home/user/.conda/envs/myenv/bin/ipython", line 7, in <module> 
    from IPython import start_ipython
  File "/home/user/.conda/envs/myenv/lib/python3.7/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/home/user/.conda/envs/myenv/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/user/.conda/envs/myenv/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 19, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
ModuleNotFoundError: No module named 'prompt_toolkit.enums'
```

For instance, the following set of commands will currently get you there:
```
conda create -n myenv python ipython
conda activate myenv
conda install python==3.7.0
conda update --all
```

This will end up in a state with `python==3.7.6`, `ipython==7.15.0`, and `prompt-toolkit==3.0.5`, but the `prompt_toolkit` package will be broken, and running `ipython` will give the above import error.

However, just running `conda create -n myenv2 python==3.7.6 ipython` will end up in completely equal state, as regards `conda list`. But `ipython` will now work.

The reason this happens is that the install of `python==3.7.0` will install `prompt_toolkit-1.0.15-py_1` alongside the already installed `prompt-toolkit-3.0.5-py_0`. Inside the `site-packages/prompt_toolkit` directory, many of the files from v3.0.5 (but not all) will be overwritten by old versions. Updating to `python==3.7.6` will remove the old `prompt_toolkit` package, which will delete the files of that version from the common `site-packages/prompt_toolkit` directory, leaving only the newer files and the package in a non-working state. But you have no way of seeing this from `conda list`, or any other kind of state (i.e. environment variables), guaranteed to cause a lot of headscratching.

This is the underlying reason for https://github.com/conda-forge/ipython-feedstock/issues/101, and will also be a problem for other conda python packages that are renamed, making this perhaps a global issue?

<br/>
Environment (<code>conda list</code>):
<details>

The non-working `myenv` and the working `myenv2` environment will have the exact same output:

```
$ conda list
# packages in environment at /home/user/.conda/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.1.1                     py_1    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                47.3.1           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(snip)
platform : linux-64
user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.10 Linux/3.10.0-1062.12.1.el7.x86_64 rhel/7.8 glibc/2.17
(snip)
```
</details>

Edit: removed duplicated content (pasted twice by mistake)

**Comment by sveinugu** [comment] 2020-06-18 00:56
@beckermr

**Comment by scopatz** [comment] 2020-06-18 01:56
FWIW I didn't like the name change

**Comment by beckermr** [comment] 2020-06-18 03:49
I’m confused as to why I am cved here. What am I missing?

**Comment by asmeurer** [comment] 2020-06-18 07:19
conda should normalize - and _ IMHO

**Comment by vallsv** [comment] 2020-06-18 12:33
It this issue related to?
- https://anaconda.org/conda-forge/prompt_toolkit/files
- https://anaconda.org/conda-forge/prompt-toolkit/files

I feel like the last ipython release pointing to the second. And all other projects pointing to the first. The constraints dependencies became a nightmare.

**Comment by beckermr** [comment] 2020-06-18 12:41
You might want to push a dummy output to the old one that simply installs the new one in addition to this PR:

https://github.com/conda-forge/ipython-feedstock/pull/106

**Comment by ocefpaf** [comment] 2020-06-18 13:55
Both names should work BTW. The issue here is probably a mixing with old version where only one name works.

> conda should normalize - and _ IMHO

Yep. Do the same as pip does. But I think that ship has sailed.

**Comment by beckermr** [comment] 2020-06-18 13:59
Right. By pushing the dummy package to the old name that installs the new one we can avoid this error.

**Comment by sveinugu** [comment] 2020-06-18 14:13
> I’m confused as to why I am cved here. What am I missing?

@beckermr Just because you created the other issue I pointed to, which I think I found the underlying reason for: https://github.com/conda-forge/ipython-feedstock/issues/101. I don't really know who are invested in what, just thought it might be of interest to you..

**Comment by beckermr** [comment] 2020-06-18 14:16
Ahhh thank you!

**Comment by sveinugu** [comment] 2020-06-18 15:15
@ocefpaf:
> Both names should work BTW. The issue here is probably a mixing with old version where only one name works.

Yes, it only happens in the probably relative rare scenario of first downgrading and then upgrading. For me it happened because I mistakenly asked for `python==3.7` instead of `python=3.7`. But I am sure there are still plenty of scenarios such an error might pop up in.

The core issue is the 2-to-1 mapping from conda package name to python package name, which should not IMHO be possible, and thus probably a structural issue (which is an opinion I have without really knowing anything about Conda internals!).

I am also quite sure this is no the first time such 2-to-1 mapping has caused problems. Any two Conda packages that somehow shares a file are prone to such errors of inconsistency. As a minimum I would, as a user, want to be notified when two installed packages contains the same files. A conservative option is to , in such cases, stop installation of packages due to "inconsistency". This might cause a bunch of issues though, depending on how common such file overlap is in practice. 

Btw: I am unsure whether the name-change was intentional or not, as I have not been able to find a discussion of the reasons for the change (except perhaps this: https://github.com/conda-forge/prompt_toolkit-feedstock/issues/23). Here is the commit:

https://github.com/conda-forge/prompt_toolkit-feedstock/pull/40/commits/950c5ceb45be366e14ac389024f0d46de22cb6f1

**Comment by scopatz** [comment] 2020-06-18 15:17
A lot of this confusion I think comes from pip, which will translate dashes to underscores. So that problem is something that we inherit for python packages with dashes in their name, because people expect the underscore version too

**Comment by sveinugu** [comment] 2020-06-18 15:39
> A lot of this confusion I think comes from pip, which will translate dashes to underscores. So that problem is something that we inherit for python packages with dashes in their name, because people expect the underscore version too

Yes, that would certainly be a common cause for such errors. What I am most worried about here is the fact that I managed to create two seemingly completely equal environments (as defined by the `conda list` output), but where one of them was not working. This seems to point to a deep structural issue with Conda, that the actual contents of a state depends on how it was reached. Having some sort of general consistency checks (think ACID transactions) might help reducing the number of strange Conda errors and make it more trustworthy.

**Comment by beckermr** [comment] 2020-06-18 16:16
Again if you make one package be an alias to the other by having it only have a run requirement to the other, this will be fixed.

**Comment by ocefpaf** [comment] 2020-06-18 16:31
@sveinugu the problem is not the name change but the lack of `run_constrained` on the metapackage with both names. I'll see if I can send a PR to fix that as soon as possible.

Note that, this problem only arises in non-common operations, like the python downgrade you showed us above. That does not mean we should not fix it soon but it means it is not a pressing issue b/c that operation does not happen too often.

**Closed** 2020-06-18 17:12 UTC

**Comment by sveinugu** [comment] 2020-06-18 18:58
> @sveinugu the problem is not the name change but the lack of `run_constrained` on the metapackage with both names. I'll see if I can send a PR to fix that as soon as possible.

 @ocefpaf Great! Thanks!

> Note that, this problem only arises in non-common operations, like the python downgrade you showed us above. That does not mean we should not fix it soon but it means it is not a pressing issue b/c that operation does not happen too often.

Yes, I agree that this scenario would happen rarely. The other PR (https://github.com/conda-forge/ipython-feedstock/pull/106) would probably happen more often, though.

My remaining concern is really a general one: whether things like this are happening too often, globally speaking. From experience, I have a feeling that Conda environments get gradually more corrupt over time, and that one should always prefer to create new environments rather than fixing old ones. As a computer scientists, this scratches an itch in me that is not healed by patching the symptoms. In practice, I feel I am not able to put my trust in Conda as much I do in, say, git (not directly comparable, but still a good counter-example). If this is a general feeling, it is not the best position to be in for a package management system. 

Of course, this is an issue for the core Conda repo. Just wanted to check if this sparked any conversation/interest here, with this issue as one example of probably many situations that end up with corrupt environments. On the other hand, there are probably other fora more suited for this type of discussion...

**Comment by asmeurer** [comment] 2020-06-18 22:41
> > conda should normalize - and _ IMHO

> Yep. Do the same as pip does. But I think that ship has sailed.

I don't see why it's sailed. Conda already normalizes case, which has saved countless hours from would-be-otherwise casing errors. Are there instances where two conda packages have the same name after replacing underscores with dashes, except in cases like this one where the same package was renamed from one to the other? Conda should just change this behavior. It might require a deprecation cycle, but I is doable. I wish we had done it 6 years ago, but I think we can still do it now.

**Comment by sveinugu** [comment] 2020-06-19 09:06
@ocefpaf 
So back to the details:
- My issue has been solved, but it seems that the issue of @vallsv remains: https://github.com/conda-forge/ipython-feedstock/pull/106#issuecomment-646471092.  I suggest we reopen this issue and continue here.

Here is the output I get when creating an env base on the command from @vallsv:
```
$ conda create -n myenv "python==3.7" "prompt-toolkit>=2" "prompt_toolkit<3"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /software/miniconda2/envs/myenv

  added / updated specs:
    - prompt-toolkit[version='>=2']
    - prompt_toolkit[version='<3']
    - python==3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    prompt_toolkit-2.0.10      |             py_0         221 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         221 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.2-hecda079_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.2-py37hc8dfbb8_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.0.2u-h516909a_0
  pip                conda-forge/noarch::pip-20.1.1-py_1
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.10-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  python             conda-forge/linux-64::python-3.7.0-hd21baee_1006
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  setuptools         conda-forge/linux-64::setuptools-47.3.1-py37hc8dfbb8_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.28.0-h8b20d00_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wcwidth            conda-forge/noarch::wcwidth-0.2.4-pyh9f0ad1d_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
```

It does not seem that the new version of the metapackage was found, should have been `prompt-toolkit-3.0.5-py_1`, right?

**Comment by sveinugu** [comment] 2020-06-19 09:11
Also, `python=3.7` gives similar resolution, so it is not connected to Python v3.7.0:
```
conda create -n myenv2 "python=3.7" "prompt-toolkit>=2" "prompt_toolkit<3"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /software/miniconda2/envs/myenv2

  added / updated specs:
    - prompt-toolkit[version='>=2']
    - prompt_toolkit[version='<3']
    - python=3.7


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.2-hecda079_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.2-py37hc8dfbb8_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_5
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  pip                conda-forge/noarch::pip-20.1.1-py_1
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.5-py_0
  prompt_toolkit     conda-forge/noarch::prompt_toolkit-2.0.10-py_0
  pygments           conda-forge/noarch::pygments-2.6.1-py_0
  python             conda-forge/linux-64::python-3.7.6-cpython_h8356626_6
  python_abi         conda-forge/linux-64::python_abi-3.7-1_cp37m
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-47.3.1-py37hc8dfbb8_0
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wcwidth            conda-forge/noarch::wcwidth-0.2.4-pyh9f0ad1d_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006
```

**Comment by sveinugu** [comment] 2020-06-19 09:17
Hmm.. Trying again to add a mention in the other issue: https://github.com/conda-forge/ipython-feedstock/pull/106

**Comment by vallsv** [comment] 2020-06-19 10:56
Could it be because this 2 file repositories differs?

- https://anaconda.org/conda-forge/prompt_toolkit/files
- https://anaconda.org/conda-forge/prompt-toolkit/files

Could it be merged together? I mean anyway one or the other should be empty right?

**Comment by ocefpaf** [comment] 2020-06-19 12:09
> I don't see why it's sailed. Conda already normalizes case, which has saved countless hours from would-be-otherwise casing errors. Are there instances where two conda packages have the same name after replacing underscores with dashes, except in cases like this one where the same package was renamed from one to the other? Conda should just change this behavior. It might require a deprecation cycle, but I is doable. I wish we had done it 6 years ago, but I think we can still do it now.

Don't tell me that @asmeurer! Tell it to the conda devs ;-p

@sveinugu and @vallsv the problem is that the change I made should be propageted to the older versions with a repo data patch. I haven't got to that yet.

**Comment by sveinugu** [comment] 2020-06-19 12:26
> @sveinugu and @vallsv the problem is that the change I made should be propageted to the older versions with a repo data patch. I haven't got to that yet.

@ocefpaf Great to hear that you are on the top of things, and sorry for the noise!

**Comment by ocefpaf** [comment] 2020-06-19 13:43
> @ocefpaf Great to hear that you are on the top of things, and sorry for the noise!

That is not noise. Thanks for the report!
